In [1]:
import numpy as np

A = np.array([[0, 1],
              [2, 3],
              [4, 5]])

B = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])

# 行列積の計算
C = np.dot(A, B)

# 結果の表示
print("行列積:")
print(C)

# 最大値の表示
print("最大値:", np.max(C))

行列積:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
最大値: 47
